theme: jekyll-theme-slate
title: '<a href="https://devs.rehab">Devs.Rehab</a>'
description: you are not alone
show_downloads: false
is_project_page: true
repository: devs-rehab/devs-rehab.github.io
plugins:
  - jemoji
